# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git z golang docker)

source $ZSH/oh-my-zsh.sh

# User configuration

# 默认编辑器
export EDITOR='vim'
export VISUAL='vim'

# Go 环境变量
export GOROOT=/usr/local/go
export GOPATH=$HOME/workspace/gopath
export GOBIN=$GOPATH/bin
export PATH=$GOROOT/bin:$GOBIN:$HOME/bin:$PATH
export GOMODCACHE=$HOME/workspace/pkg/go

# 语言和编码
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export PYTHONIOENCODING=utf-8

# 自定义别名
command -v claude-internal &>/dev/null && alias claude="claude-internal"

# CodeBuddy
export PATH="$HOME/.codebuddy/bin:$PATH"

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
